<?php

    use \xtodx\serializecache\SerializeCache;

    class CacheTest extends PHPUnit\Framework\TestCase
    {

        public function setUp()
        {
            SerializeCache::setPath(PATH);
        }


        public function testSave()
        {
            ob_start();
            SerializeCache::save("menu", ["/", "HOME", "/test/", "TEST"]);
            ob_end_clean();
            $this->assertEquals(1, 1);
        }

        /**
         * @depends testSave
         */
        public function testFirst()
        {
            ob_start();
            $data = SerializeCache::open("menu");
            ob_end_clean();
            if ($data) {
                $this->assertEquals(1, 1);
            }else{
                $this->assertEquals(0, 1);
            }
        }


        public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
        }
    }